# Here the name corresponds to class name of torch.optim classes
# The options are the ones of the torch.optim class (e.g., learning rate is `lr` not `learning_rate` or other)
# see https://pytorch.org/docs/stable/optim.html

optimizer:
    name: Adam
    depth_net_options: # optimizer's options for the depth network
      lr: 0.0002
    pose_net_options: # optimizer's options for the pose network
      lr: 0.0002