includes:
  - base.yml

project_name: Submissiong_ArgoPT_MonocularDepthKitti # will also be used as wandb project name
experiment_name: self_supervised # will also be used as wandb experiment name, each run have a unique id