includes:
  - base.yml

project_name: Test_Supervised_Methods # will also be used as wandb project name
experiment_name: test_supervised # will also be used as wandb experiment name, each run have a unique id