includes:
  - attention_guiding_res_sig_resnet18.yml

model:
  depth_net:
    options:
      attention_scheme: 'concat-mult-sig'
      upsample_mode: 'pixelshuffle'
      blur: True
      blur_at_end: True