model:
  tri_checkpoint_path: ???
  depth_net:
    name: guiding
    options:
      guidance: attention
      num_layers: 18      # choices=[18, 34, 50, 101, 152]
      attention_scheme: 'res-sig'
      two_encoder: True
  pose_net:
    name: monodepth
    options:
      num_layers: 18