input_channels: 3

model:
  tri_checkpoint_path: ???
  depth_net:
    name: mfmp_symmetric
    options:
      activation: elu
      image_extractor_name: resnet
      image_extractor_hparams:
        version: 18        # choices=[18, 34, 50, 101, 152]
        input_channels: ${input_channels}
        zero_init_residual: False
      lidar_extractor_name: lidar-resnet
      lidar_extractor_hparams:
        version: 18        # choices=[18, 34, 50, 101, 152]
        input_channels: ${input_channels}
        zero_init_residual: False
        small: False
      decoder_hparams:
        scales: 4
        predictor: inv_depth
        upsample_mode: nearest
      fusion_name: concat
  pose_net:
    name: monodepth2
    options:
      version: 18
      activation: elu
      input_channels: ${input_channels}