input_channels: 3

model:
  tri_checkpoint_path: ???
  depth_net:
    name: monodepth2
    options:
      activation: elu
      encoder_options:
        version: 18        # choices=[18, 34, 50, 101, 152]
        input_channels: ${input_channels}
        zero_init_residual: False
      decoder_options:
        scales: 4
        predictor: inv_depths
        upsample_mode: nearest
  pose_net:
    name: monodepth2
    options:
      version: 18
      activation: elu
      input_channels: ${input_channels}