model:
  tri_checkpoint_path: ???
  depth_net:
    name: sparse-guiding
    options:
      guidance: attention
      attention_scheme: 'res-sig'
      dilation_rates: [[1,2,4,8],[1,2,4,8],[1,4,8,16],[1,4,8,16]]
  pose_net:
    name: monodepth
    options:
      num_layers: 18