model:
  tri_checkpoint_path: ???
  depth_net:
    name: sparse-guiding
    options:
      guidance: attention
      attention_scheme: 'res-sig'
  pose_net:
    name: monodepth
    options:
      num_layers: 18