image_input_channels: 3

network:
  tri_checkpoint_path: ???
  depth_net:
    name: MFMP_symmetric
    options:
      activation: elu
      image_extractor_name: resnet
      image_extractor_hparams:
        version: 18        # choices=[18, 34, 50, 101, 152]
        input_channels: ${image_input_channels}
        zero_init_residual: False
      lidar_extractor_name: lidar-resnet
      lidar_extractor_hparams:
        version: 18        # choices=[18, 34, 50, 101, 152]
        input_channels: 1
        zero_init_residual: False
        small: False
      decoder_hparams:
        predictor: inv_depth
        upsample_mode: nearest
      fusion_name: concat
  pose_net:
    name: monodepth2
    options:
      version: 18
      activation: elu
      input_channels: ${image_input_channels}