losses:
    HintedMultiViewPhotometricLoss:
      num_scales: 4                   # Number of inverse depth scales to use
      ssim_loss_weight: 0.85          # SSIM loss weight
      occ_reg_weight: 0.1             # Occlusion regularizer loss weight
      smooth_loss_weight: 0.001       # Smoothness loss weight
      uniformity_weight: 0.0
      uniformity_threshold: 0.05
      C1: 1e-4                        # SSIM parameter
      C2: 9e-4                        # SSIM parameter
      photometric_reduce_op: min    # Method for photometric loss reducing
      disp_norm: True                 # Inverse depth normalization
      clip_loss: 0.0                  # Clip loss threshold variance
      progressive_scaling: 0.0        # Training percentage to decay number of scales
      padding_mode: zeros           # Photometric loss padding mode
      automask_loss: True             # Automasking to remove static pixels