# only for convenience purpose, not used internally
argoverse_tracking_root_dir: /home/clear/fbartocc/data/ARGOVERSE/argoverse-tracking
splits_base_dir: /home/clear/fbartocc/output_data/MultiCamDepth/MultiCamMonoDepthArgo
depth_root_dir: /home/clear/fbartocc/working_data/Argoverse_projected_lidar
sparse_depth_root_dir: /home/clear/fbartocc/working_data/Argoverse_sparse_projected_lidar

datasets:
    dataset_name: rand_cam_argoverse
    train:
      argoverse_tracking_root_dir: ${argoverse_tracking_root_dir}
      split_file: ${splits_base_dir}/non_static_train_ring_source_views_indexes_-1_1.pkl
      sparse_depth_root_dir: ${sparse_depth_root_dir}
      depth_root_dir: ${depth_root_dir}
      load_pose: False
      data_transform_options: # augmentation options
        image_shape: [480, 768] # 1200 * 8/10 / 2, 1920 * 8/10 / 2 so that they are divisible by 32
        jittering: [0.2, 0.2, 0.2, 0.05]

    val:
      argoverse_tracking_root_dir: ${argoverse_tracking_root_dir}
      split_file: ${splits_base_dir}/val_ring_source_views_indexes_.pkl
      sparse_depth_root_dir: ${sparse_depth_root_dir}
      depth_root_dir: ${depth_root_dir}
      data_transform_options: # augmentation options
        image_shape: [960, 1536] # 1200, 1920 * 8/10

    test:
      argoverse_tracking_root_dir: ${argoverse_tracking_root_dir}
      split_file: ${splits_base_dir}/test_ring_source_views_indexes_.pkl
      sparse_depth_root_dir: ${sparse_depth_root_dir}
      depth_root_dir: ${depth_root_dir}
      data_transform_options: # augmentation options
        image_shape: [960, 1536] # 1200, 1920 * 8/10